language: csharp
solution: Mandrill.net.sln
install:
  - nuget restore Mandrill.net.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory packages
script:
  - xbuild /p:Configuration=Release Mandrill.net.sln
  - mono ./packages/NUnit.Runners.2.6.4/tools/nunit-console.exe -noxml -nodots -labels ./tests/Tests/bin/Release/Tests.dll