
os: Visual Studio 2015
environment:
  VisualStudioVersion: 14.0
  matrix:
    - runtime: coreclr
    - runtime: clr
install:
  - dnvm upgrade -r %runtime%
  - dnu restore
  - dnu pack src/Mandrill.net --configuration Release --out artifacts
  - cd ./tests/Tests
  - dnx test --labels=All --verbose --where:cat!=exports
build: off
artifacts:
  - path: artifacts\**\*.nupkg
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
    runtime: clr
  api_key:
    secure: yYZGBnyhi9s3qBjVh9KhSnneM/qVxkGiSfNkXWekPyMFSFbDYYoXiuZxwMAQm8YV
  skip_symbols: false
  artifact: /.*\.nupkg/
