
os: Visual Studio 2015
environment:
  VisualStudioVersion: 14.0
  COVERALLS_REPO_TOKEN:
    secure: JD6RZJ00/a4C5TBIzQSE6SHQun3o04wdgSyz4+uu6QFGtoWFcQuqag21+IUzY95f
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-$(appveyor_repo_commit)"
before_build:
  - dotnet --version
  - where dotnet
  - dotnet restore
  - ps: >-
      (Get-Content src\Mandrill.net\project.json).replace('"version": "1.0.0-*",', '"version": "' + $env:APPVEYOR_BUILD_VERSION + $env:PRERELEASE_TAG +'",') | Set-Content src\Mandrill.net\project.json
  - nuget install OpenCover -version 4.6.519 -OutputDirectory .\packages
  - nuget install coveralls.io -version 1.3.4 -OutputDirectory .\packages
build: off
build_script:
  - dotnet build **/project.json
  - dotnet pack src/Mandrill.net --configuration Release --output artifacts
test: off
test_script:
  - if defined APPVEYOR_PULL_REQUEST_NUMBER dotnet test ./tests/Tests --where:cat!=integration
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -oldStyle -register:user -filter:"+[*]Mandrill* -[Tests]*" -target:"C:\\Program Files\\dotnet\\dotnet.exe" -targetargs:"test ./tests/Tests" -skipautoprops -hideskipped:All -output:coverage.xml
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
  - path: artifacts\**\*.nupkg
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: yYZGBnyhi9s3qBjVh9KhSnneM/qVxkGiSfNkXWekPyMFSFbDYYoXiuZxwMAQm8YV
  skip_symbols: false
  artifact: /.*\.nupkg/
