
os: Visual Studio 2017
environment:
  VisualStudioVersion: 15.0
  COVERALLS_REPO_TOKEN:
    secure: JD6RZJ00/a4C5TBIzQSE6SHQun3o04wdgSyz4+uu6QFGtoWFcQuqag21+IUzY95f
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
before_build:
  - dotnet --version
  - where dotnet
  - dotnet restore
  # - nuget install OpenCover -version 4.6.519 -OutputDirectory .\packages
  # - nuget install coveralls.io -version 1.3.4 -OutputDirectory .\packages
build: off
build_script:
  - dotnet pack src/Mandrill.net --configuration Release --output artifacts
test: off
test_script:
  - if defined MANDRILL_API_KEY dotnet test tests/Tests/Tests.csproj
  # - if defined MANDRILL_API_KEY ..\..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]Mandrill* -[Tests]*" -target:"C:\\Program Files\\dotnet\\dotnet.exe" -targetargs:"test tests/Tests/Tests.csproj" -skipautoprops -output:coverage.xml
  # - if defined MANDRILL_API_KEY  ..\..\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: yYZGBnyhi9s3qBjVh9KhSnneM/qVxkGiSfNkXWekPyMFSFbDYYoXiuZxwMAQm8YV
  skip_symbols: false
  artifact: /.*\.nupkg/
