
os: Visual Studio 2015
environment:
  VisualStudioVersion: 14.0
  matrix:
    - runtime: coreclr
    - runtime: clr
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-{appveyor_repo_commit}"
before_build:
  - dnvm upgrade -r %runtime%
  - dnu restore
build: off
build_script:
  - dnu pack src/Mandrill.net --configuration Release --out artifacts
test: off
test_script:
  - cd ./tests/Tests
  - dnx test --labels=All --verbose --where:cat!=exports
artifacts:
  - path: artifacts\**\*.nupkg
deploy:
  provider: NuGet
  on:
    branch: master
    appveyor_repo_tag: true
    runtime: clr
  api_key:
    secure: yYZGBnyhi9s3qBjVh9KhSnneM/qVxkGiSfNkXWekPyMFSFbDYYoXiuZxwMAQm8YV
  skip_symbols: false
  artifact: /.*\.nupkg/
